#!/bin/bash
# QUICK START - EPO 316 Base de Datos MySQL

echo "🚀 GUÍA RÁPIDA - EPO 316 Base de Datos"
echo "======================================"
echo ""
echo "1️⃣  INICIAR XAMPP"
echo "   - Abre Xampp Control Panel"
echo "   - Inicia: Apache ✓ MySQL ✓"
echo ""
echo "2️⃣  CREAR BASE DE DATOS"
echo "   - Ve a: http://localhost/phpmyadmin"
echo "   - Usuario: root (sin contraseña)"
echo "   - Nueva BD: epo_316_crud"
echo "   - Collation: utf8mb4_unicode_ci"
echo ""
echo "3️⃣  EJECUTAR SCRIPTS SQL"
echo "   - En phpMyAdmin > SQL"
echo "   - Copia: scripts/setup-database.sql"
echo "   - Luego: scripts/ejemplo_datos.sql"
echo ""
echo "4️⃣  INICIAR SERVIDOR"
echo "   - npm run dev"
echo "   - Ve a: http://localhost:3000/admin/login"
echo ""
echo "5️⃣  CREDENCIALES"
echo "   - Correo: admin@epo316.edu.mx"
echo "   - Contraseña: admin123"
echo ""
echo "✅ ¡Todo listo!"
echo ""
echo "📝 NOTAS:"
echo "   - Las tablas están en ESPAÑOL"
echo "   - Los nombres de columnas están en ESPAÑOL"
echo "   - Todos los datos de ejemplo también"
echo ""
echo "📊 TABLAS CREADAS:"
echo "   ✓ usuarios (administradores)"
echo "   ✓ estudiantes"
echo "   ✓ calificaciones"
echo "   ✓ anuncios"
echo "   ✓ estadisticas_escuela"
echo ""
